In [14]:
import tensorflow as tf
from tensorflow import keras

In [15]:
(x_train,y_train),(x_test,y_test)=keras.datasets.mnist.load_data()

In [16]:
x_train[1000]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,  36, 146, 254, 255, 251,  95,   6,   0,   0,   0,   0,   0,
          0,   0],
       [  

In [17]:
y_train[1000]

np.uint8(0)

In [18]:
x_train=x_train/255.0 #normailization
x_test=x_test/255.0

In [19]:
print(x_train[0])

[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.    

In [31]:
#buiding neural network
model=keras.Sequential([
    keras.layers.Flatten(input_shape=(28,28)), #convert into one dimension data 28+28=784 [para 0 no calculations are performed 
    keras.layers.Dense(128,activation='relu'),
    keras.layers.Dense(10,activation='softmax')
])
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ flatten_1 (Flatten)                  │ (None, 784)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 128)                 │         100,480 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 10)                  │           1,290 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 101,770 (397.54 KB)

 Trainable params: 101,770 (397.54 KB)

 Non-trainable params: 0 (0.00 B)

In [32]:
#compile
model.compile(optimizer="adam",loss="sparse_categorical_crossentropy",metrics=["accuracy"])

In [35]:
#train model
model.fit(x_train,y_train,epochs=5,validation_data=(x_test,y_test))

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 13s 7ms/step - accuracy: 0.9957 - loss: 0.0136 - val_accuracy: 0.9770 - val_loss: 0.0911
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 20s 7ms/step - accuracy: 0.9963 - loss: 0.0117 - val_accuracy: 0.9770 - val_loss: 0.0884
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 20s 7ms/step - accuracy: 0.9970 - loss: 0.0102 - val_accuracy: 0.9767 - val_loss: 0.0914
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 21s 7ms/step - accuracy: 0.9973 - loss: 0.0086 - val_accuracy: 0.9786 - val_loss: 0.0923
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 20s 7ms/step - accuracy: 0.9981 - loss: 0.0068 - val_accuracy: 0.9777 - val_loss: 0.0949


In [36]:
#evaluate
model.evaluate(x_test,y_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9777 - loss: 0.0949


[0.09492994099855423, 0.9776999950408936]

In [37]:
loss,accuracy=model.evaluate(x_test,y_test)
print("loss=",loss)
print("accuracy=",accuracy)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9777 - loss: 0.0949
loss= 0.09492994099855423
accuracy= 0.9776999950408936


In [25]:
import numpy as np
sample_image=x_test[0]
sample_label=y_test[0]
sample_image

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.    

In [29]:
#add batch dimensions
sample_image=np.expand_dims(sample_image,axis=0)

In [32]:
predictions=model.predict(sample_image)
predicted_digit=np.argmax(predictions)
print("prediction digit:",predicted_digit)
print("actual digit:",sample_label)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step
prediction digit: 7
actual digit: 7


In [33]:
predictions

array([[5.6433311e-08, 2.4041054e-07, 2.3012169e-04, 4.9248023e-04,
        4.3661821e-11, 1.2947050e-06, 1.7495174e-11, 9.9927002e-01,
        3.4250183e-06, 2.3988068e-06]], dtype=float32)

In [26]:
from tensorflow.keras.preprocessing import image
img=image.load_img(
    "sev.png",
    color_mode="grayscale",
    target_size=(28,28)

)

In [27]:
img_array=image.img_to_array(img)
img_array=img_array/255.0
img_array=img_array.reshape(1,28,28)

In [28]:
prediction=model.predict(img_array)
predicted_digit=np.argmax(prediction)
print("predicted digit:",predicted_digit)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 159ms/step
predicted digit: 2


In [30]:
confidence=np.max(prediction)*100
print(f"confidence:{confidence:.2f}%")

confidence:100.00%
